[versions]
kotlin = "2.2.21"
junit = "6.0.1"
jmh = "1.37"

[libraries]
jdbc-h2 = { module = "com.h2database:h2", version = "2.4.240" }
jdbc-mysql = { module = "mysql:mysql-connector-java", version = "8.0.33" }
jdbc-oracle = { module = "com.oracle.database.jdbc:ojdbc11", version = "23.26.0.0.0" }
jdbc-postgresql = { module = "org.postgresql:postgresql", version = "42.7.8" }
jdbc-sqlite = { module = "org.xerial:sqlite-jdbc", version = "3.51.0.0" }
jdbc-sqlserver = { module = "com.microsoft.sqlserver:mssql-jdbc", version = "12.10.2.jre11" }

slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.20" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
apiguardian = { module = "org.apiguardian:apiguardian-api", version = "1.1.2" }

testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version = "2.0.1" }
testcontainers-mysql = { module = "org.testcontainers:testcontainers-mysql" }
testcontainers-oracle = { module = "org.testcontainers:testcontainers-oracle-xe" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
testcontainers-sqlserver = { module = "org.testcontainers:testcontainers-mssqlserver" }

ecj = { module = "org.eclipse.jdt:ecj", version = "3.43.0" }

jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }

google-java-format = { module = "com.google.googlejavaformat:google-java-format", version = "1.28.0" }
ktlint = { module = "com.pinterest.ktlint:ktlint-cli", version = "1.7.1" }

quarkus-doma = { module = "io.quarkiverse.doma:quarkus-doma", version = "1.0.6"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
release = { id = "net.researchgate.release", version = "3.1.0" }
doma-compile = { id = "org.domaframework.doma.compile", version = "4.0.3" }
doma-codegen = { id = "org.domaframework.doma.codegen", version = "3.2.1" }
shadow = { id = "com.gradleup.shadow", version = "9.2.2" }
themrmilchmann-ecj = { id = "io.github.themrmilchmann.ecj", version = "0.2.0" }
jmh = { id = "me.champeau.jmh", version = "0.7.3" }
eclipse-apt = { id = "com.diffplug.eclipse.apt", version = "4.4.1" }
