name: Changelog

on:
  release:
    types: 
      - released

jobs:
  changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Prepare ENV variables
        run: |
          body=$(jq '.release.body' $GITHUB_EVENT_PATH)
          html_url=$(jq '.release.html_url' $GITHUB_EVENT_PATH)
          name=$(jq '.release.name' $GITHUB_EVENT_PATH)
          echo "ORG_GRADLE_PROJECT_releaseBody=$body" >> $GITHUB_ENV
          echo "ORG_GRADLE_PROJECT_releaseHtmlUrl=$html_url" >> $GITHUB_ENV
          echo "ORG_GRADLE_PROJECT_releaseName=$name" >> $GITHUB_ENV

      - name: Update CHANGELOG.md
        uses: gradle/gradle-build-action@v2
        with:
          arguments: updateChangelog

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          branch: master
          message: "Update CHANGELOG.md"
          add: "CHANGELOG.md"
